import uuid
from datetime import datetime
from decimal import Decimal
from typing import List, Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class PurchaseOrder(Base):
    """
    Legally binding procurement contract generated from an approved Quotation.
    UNIQUE on quotation_id — one approved quotation yields exactly one PO.
    Status lifecycle: generated → completed | cancelled
    is_locked prevents edits once the Invoice is raised.
    doc_number is auto-generated by DB trigger: PO-YYYY-NNN
    """

    __tablename__ = "purchase_orders"

    po_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    doc_number: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    quotation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("quotations.quotation_id", ondelete="RESTRICT"),
        nullable=False,
        unique=True,
        index=True,
    )
    created_by_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.user_id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="generated"
    )  # CHECK: generated | completed | cancelled
    total_amount: Mapped[Decimal] = mapped_column(Numeric(15, 2), nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="USD")
    tax_rate: Mapped[Decimal] = mapped_column(
        Numeric(5, 2), nullable=False, default=Decimal("0.00")
    )
    is_locked: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── The approved quotation this PO was generated from (1:1) ───────────
    quotation: Mapped["Quotation"] = relationship(
        "Quotation", back_populates="purchase_order"
    )

    # ── The officer who generated this PO ──────────────────────────────────
    created_by: Mapped["User"] = relationship(
        "User",
        foreign_keys=[created_by_id],
        back_populates="created_purchase_orders",
    )

    # ── Snapshotted line items copied from quotation at PO creation (1:N) ──
    # These are immutable snapshots — they do NOT reference live catalog data.
    items: Mapped[List["PurchaseOrderItem"]] = relationship(
        "PurchaseOrderItem",
        back_populates="purchase_order",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    # ── Invoice raised against this PO (1:1, optional until billed) ────────
    invoice: Mapped[Optional["Invoice"]] = relationship(
        "Invoice",
        back_populates="purchase_order",
        uselist=False,
    )


class PurchaseOrderItem(Base):
    """
    Immutable snapshot of a line item at the time the Purchase Order was created.
    Decoupled from live catalog data to preserve audit integrity.
    DB CHECK enforces: total_price = quantity * unit_price.
    Deleted when parent PO is deleted (ON DELETE CASCADE).
    """

    __tablename__ = "purchase_order_items"

    po_item_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    po_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("purchase_orders.po_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    item_name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    quantity: Mapped[Decimal] = mapped_column(Numeric(15, 4), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Numeric(15, 2), nullable=False)
    total_price: Mapped[Decimal] = mapped_column(Numeric(15, 2), nullable=False)

    # ── Parent purchase order ──────────────────────────────────────────────
    purchase_order: Mapped["PurchaseOrder"] = relationship(
        "PurchaseOrder", back_populates="items"
    )
